In [4]:
import numpy as np

# Define the matrix
A = np.array([[3, 4, -1],
              [1, 0, 3],
              [2, 5, -4]])



In [5]:
# 1. Determinant
det_A = np.linalg.det(A)
print(f"Determinant of A: {det_A:.0f}")

# 2. Adjoint = Transpose of cofactor matrix
def adjoint(matrix):
    cofactors = np.zeros(matrix.shape)
    for row in range(matrix.shape[0]):
        for col in range(matrix.shape[1]):
            # Minor matrix
            minor = np.delete(np.delete(matrix, row, axis=0), col, axis=1)
            # Cofactor with sign
            cofactors[row, col] = ((-1) ** (row + col)) * np.linalg.det(minor)
    return cofactors.T  # Transpose to get adjoint

adj_A = adjoint(A)
print("\nAdjoint of A:")
print(adj_A)

# 3. Inverse (if determinant is not zero)
if det_A != 0:
    inv_A = np.linalg.inv(A)
    print("\nInverse of A:")
    print(inv_A)
else:
    print("\nMatrix is singular, no inverse exists.")


Determinant of A: -10

Adjoint of A:
[[-15.  11.  12.]
 [ 10. -10. -10.]
 [  5.  -7.  -4.]]

Inverse of A:
[[ 1.5 -1.1 -1.2]
 [-1.   1.   1. ]
 [-0.5  0.7  0.4]]


In [6]:
rank_A = np.linalg.matrix_rank(A)
print(f"Rank: {rank_A}")

Rank: 3
